"""update task category field type

Revision ID: bafe5879d20f
Revises: 76e7234cc8af
Create Date: 2025-01-18 01:13:31.957926+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bafe5879d20f'
down_revision = '76e7234cc8af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_history_id', table_name='chat_history')
    op.drop_table('chat_history')
    op.alter_column('categorized_entries', 'chat_history_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('categorized_entries', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('categorized_entries', 'category',
               existing_type=postgresql.ENUM('todo', 'idea', 'thought', 'time_record', name='content_category'),
               type_=sa.Enum('todo', 'idea', 'thought', 'time_record', name='contentcategory'),
               existing_nullable=False)
    op.alter_column('categorized_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_constraint('categorized_entries_chat_history_id_fkey', 'categorized_entries', type_='foreignkey')
    op.create_foreign_key(None, 'categorized_entries', 'chat_histories', ['chat_history_id'], ['id'])
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'category',
               existing_type=postgresql.ENUM('TODO', 'MEETING', 'BREAK', 'OTHER', name='task_category'),
               type_=sa.Enum('TODO', 'MEETING', 'BREAK', 'OTHER', name='taskcategory'),
               existing_nullable=False)
    op.alter_column('tasks', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('tasks', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tasks', 'duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tasks', 'duration',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('tasks', 'end_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tasks', 'start_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tasks', 'category',
               existing_type=sa.Enum('TODO', 'MEETING', 'BREAK', 'OTHER', name='taskcategory'),
               type_=postgresql.ENUM('TODO', 'MEETING', 'BREAK', 'OTHER', name='task_category'),
               existing_nullable=False)
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'categorized_entries', type_='foreignkey')
    op.create_foreign_key('categorized_entries_chat_history_id_fkey', 'categorized_entries', 'chat_history', ['chat_history_id'], ['id'])
    op.alter_column('categorized_entries', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('categorized_entries', 'category',
               existing_type=sa.Enum('todo', 'idea', 'thought', 'time_record', name='contentcategory'),
               type_=postgresql.ENUM('todo', 'idea', 'thought', 'time_record', name='content_category'),
               existing_nullable=False)
    op.alter_column('categorized_entries', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('categorized_entries', 'chat_history_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('chat_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('audio_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chat_history_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_history_pkey')
    )
    op.create_index('ix_chat_history_id', 'chat_history', ['id'], unique=False)
    # ### end Alembic commands ###
